# Generated by Django 5.1.1 on 2024-11-18 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta', 'Tarjeta'), ('PayPal', 'PayPal'), ('Vale', 'Vale')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vale', models.CharField(max_length=255)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_vale', to='payments.pago')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=255)),
                ('no_tarjeta', models.CharField(max_length=16)),
                ('fecha_vencimiento', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=4)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_tarjeta', to='payments.pago')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_titular', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_paypal', to='payments.pago')),
            ],
        ),
    ]
