# Generated by Django 5.1.1 on 2024-10-29 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(default='SIN_CODIGO', max_length=20, unique=True),
        ),
    ]
