# Generated by Django 5.1.1 on 2024-10-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_producto_codigo_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='codigo_producto',
            field=models.CharField(blank=True, max_length=13, unique=True),
        ),
    ]
