# Generated by Django 5.1.1 on 2024-10-29 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_producto_codigo_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacionproducto',
            name='cantidad',
        ),
        migrations.AlterField(
            model_name='almacen',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
