# Generated by Django 4.2.16 on 2024-10-07 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RRHH", "0003_departamento_sucursal_puesto_departamento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="departamento",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="RRHH.sucursal"
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="departamento",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="RRHH.departamento",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="empleado",
            name="puesto",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="RRHH.puesto"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="empleado",
            name="sucursal",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="RRHH.sucursal",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="puesto",
            name="departamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="RRHH.departamento"
            ),
        ),
        migrations.AlterField(
            model_name="sucursal",
            name="direccion",
            field=models.CharField(max_length=200),
        ),
    ]
