# Generated by Django 4.2.16 on 2024-10-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RRHH", "0004_alter_departamento_sucursal_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="empleado",
            name="contraseña",
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="empleado",
            name="folioEmpleado",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
