# Generated by Django 4.2.16 on 2024-10-12 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("RRHH", "0005_empleado_contraseña_empleado_folioempleado"),
    ]

    operations = [
        migrations.CreateModel(
            name="Percepciones",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Salida_Entrada",
            fields=[
                (
                    "codigo_empleado",
                    models.CharField(max_length=5, primary_key=True, serialize=False),
                ),
                ("hora", models.DateTimeField()),
                (
                    "opcion",
                    models.CharField(
                        choices=[("E", "Entrada"), ("S", "Salida")], max_length=1
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nomina",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("fecha_pago", models.DateField(verbose_name="Fecha de pago")),
                (
                    "salario_diario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salario diario"
                    ),
                ),
                ("dias_trabajados", models.IntegerField()),
                ("dias_pagados", models.IntegerField()),
                ("fecha_inicial", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_final", models.DateField(verbose_name="Fecha final")),
                (
                    "tiponomina",
                    models.CharField(
                        choices=[
                            ("S", "Semanal"),
                            ("Q", "Quincenal"),
                            ("M", "Mensual"),
                            ("A", "Anual"),
                            ("AG", "Aguinaldo"),
                            ("O", "Ordinario"),
                            ("F", "Finiquito"),
                        ],
                        max_length=2,
                    ),
                ),
                ("descontar_ahorro", models.BooleanField()),
                ("monto_DA", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descontar_prestamo", models.BooleanField()),
                ("monto_DP", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_percepciones",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("deducciones", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "salario_final",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RRHH.departamento",
                    ),
                ),
                (
                    "folioEmpleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nomina_folioEmpleado",
                        to="RRHH.empleado",
                    ),
                ),
                (
                    "nombre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nomina_nombre",
                        to="RRHH.empleado",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="RRHH.puesto"
                    ),
                ),
            ],
        ),
    ]
