# Generated by Django 5.1.1 on 2024-12-01 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_chatgroup_groupmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='users_online',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
    ]
