# Generated by Django 5.1.1 on 2024-12-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_remove_chatgroup_admin_remove_chatgroup_is_private_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='groupchat_name',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
