# Generated by Django 5.1.1 on 2024-12-01 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_chatgroup_admin_chatgroup_groupchat_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroup',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='groupchat_name',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='is_private',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='members',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='users_online',
        ),
        migrations.RemoveField(
            model_name='groupmessage',
            name='file',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
