# Generated by Django 5.1.1 on 2024-12-02 02:40

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_alter_chatgroup_group_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='is_privated',
            new_name='is_private',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_name',
            field=models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=128, unique=True),
        ),
    ]
