# Generated by Django 4.2.16 on 2024-11-04 04:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("apellidos", models.CharField(max_length=100)),
                ("numero", models.CharField(max_length=15)),
                ("fecha_nac", models.DateField(verbose_name="Fecha de nacimiento")),
                (
                    "estado_civil",
                    models.CharField(
                        choices=[
                            ("S", "Soltero/a"),
                            ("C", "Casado/a"),
                            ("D", "Divorciado/a"),
                            ("V", "Viudo/a"),
                        ],
                        max_length=1,
                    ),
                ),
                ("edad", models.IntegerField()),
                ("correo", models.EmailField(max_length=254)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                        max_length=1,
                    ),
                ),
                ("rfc", models.CharField(max_length=13)),
                ("curp", models.CharField(max_length=18)),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="fotos_empleados/"
                    ),
                ),
                (
                    "Username",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RRHH.departamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Percepciones",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=3, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("monto", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Sucursal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Salida_Entrada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora", models.DateTimeField(auto_now_add=True)),
                (
                    "opcion",
                    models.CharField(
                        choices=[("E", "Entrada"), ("S", "Salida")], max_length=1
                    ),
                ),
                (
                    "codigo_empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="RRHH.empleado"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Puesto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RRHH.departamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nomina",
            fields=[
                (
                    "codigo",
                    models.CharField(max_length=6, primary_key=True, serialize=False),
                ),
                ("fecha_pago", models.DateField(verbose_name="Fecha de pago")),
                (
                    "salario_diario",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Salario diario"
                    ),
                ),
                ("dias_trabajados", models.IntegerField()),
                ("dias_pagados", models.IntegerField()),
                ("fecha_inicial", models.DateField(verbose_name="Fecha de inicio")),
                ("fecha_final", models.DateField(verbose_name="Fecha final")),
                (
                    "tiponomina",
                    models.CharField(
                        choices=[
                            ("S", "Semanal"),
                            ("Q", "Quincenal"),
                            ("M", "Mensual"),
                            ("A", "Anual"),
                            ("AG", "Aguinaldo"),
                            ("O", "Ordinario"),
                            ("F", "Finiquito"),
                        ],
                        max_length=2,
                    ),
                ),
                ("descontar_ahorro", models.BooleanField()),
                ("monto_DA", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descontar_prestamo", models.BooleanField()),
                ("monto_DP", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "total_percepciones",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("deducciones", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Subtotal"
                    ),
                ),
                (
                    "salario_final",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Total"
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="RRHH.departamento",
                    ),
                ),
                (
                    "folioEmpleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nomina_folioEmpleado",
                        to="RRHH.empleado",
                    ),
                ),
                (
                    "nombre",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nomina_nombre",
                        to="RRHH.empleado",
                    ),
                ),
                (
                    "puesto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="RRHH.puesto"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="empleado",
            name="puesto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="RRHH.puesto"
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="RRHH.sucursal"
            ),
        ),
        migrations.AddField(
            model_name="departamento",
            name="sucursal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="RRHH.sucursal"
            ),
        ),
    ]
