# Generated by Django 5.1.1 on 2024-10-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ecar", "0002_alter_carritoproducto_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="carritoproducto",
            unique_together=set(),
        ),
    ]
