# Generated by Django 5.1.1 on 2024-11-02 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecar", "0003_alter_carritoproducto_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="descuento",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
