# Generated by Django 5.1.2 on 2024-11-01 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=16)),
                ('telefono', models.CharField(max_length=15)),
                ('caja', models.IntegerField()),
                ('rol', models.CharField(choices=[('ADM', 'Administrador'), ('BDG', 'Empleado Bodega'), ('CAJ', 'Empleado Caja'), ('GEB', 'Gerente de Bodega')], default='BDG', max_length=3)),
                ('idsucursal', models.CharField(choices=[('URI', 'Uriangato'), ('PURU', 'Puruandiro'), ('YURI', 'Yuriria')], default='URI', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Mi Ejemplo de Chanagrro', max_length=100)),
                ('numTel', models.CharField(default='000-000-0000', max_length=15)),
                ('direccion', models.CharField(default='Avenida 123, Mich', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(default='ta muy rico', max_length=255)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField()),
                ('descuento', models.PositiveIntegerField()),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.sucursal')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(default='Pedro Guapo')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.empleado')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.sucursal')),
            ],
        ),
    ]
