# Generated by Django 5.1.2 on 2024-11-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='imagen', upload_to='pos/static/img/'),
            preserve_default=False,
        ),
    ]
