# Generated by Django 5.1.2 on 2024-11-09 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_alter_venta_descripcion_detalleventa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
    ]
