# Generated by Django 5.1.1 on 2024-10-07 00:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('rfc', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='FacturaPorCobrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('importe', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Vencida', 'Vencida'), ('Pagada', 'Pagada')], default='Pendiente', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='GestionDisputaDePagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_disputado', models.IntegerField()),
                ('estado', models.CharField(choices=[('En proceso', 'En proceso'), ('Pendiente', 'Pendiente'), ('Finalizado', 'Finalizado'), ('Cancelado', 'Cancelado')], default='Pendiente', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia'), ('Tarjeta', 'Tarjeta'), ('PayPal', 'PayPal'), ('Vale', 'Vale')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Efectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagos.pago')),
            ],
        ),
        migrations.CreateModel(
            name='PayPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('estado_de_cuenta', models.CharField(choices=[('activa', 'Activa'), ('suspendida', 'Suspendida'), ('cerrada', 'Cerrada')], max_length=20)),
                ('metodo_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagos.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_tarjeta', models.CharField(max_length=16)),
                ('fecha_vencimiento', models.CharField(max_length=7)),
                ('cvv', models.CharField(max_length=4)),
                ('metodo_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagos.pago')),
            ],
        ),
        migrations.CreateModel(
            name='Vale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vale', models.CharField(max_length=255)),
                ('metodo_pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagos.pago')),
            ],
        ),
    ]
