# Generated by Django 5.1.1 on 2024-10-06 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_point', models.CharField(help_text='Dirección de inicio', max_length=255)),
                ('destination', models.CharField(help_text='Dirección de destino', max_length=255)),
                ('estimated_time', models.IntegerField(blank=True, help_text='Tiempo estimado en minutos', null=True)),
                ('distance', models.FloatField(blank=True, help_text='Distancia en kilómetros', null=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route', to='shipments.order')),
            ],
        ),
    ]
